db:
  image: postgres:9.4.1
  ports:
    - "5432:5432"

web:
  build: .
  command: bin/rails server --port 3000 --binding 0.0.0.0
  ports:
    - "3000:3000"
  links:
    - db
  volumes:
    - .:/airsched
  # This tells the web container to mount the `bundle` images'
  # /bundle volume to the `web` containers /bundle path.
  volumes_from:
    - bundle

# --- Add this to your fig.yml or docker-compose.yml file ---
bundle:
  # 'image' will vary depending on your docker-compose 
  # project name. You may need to run `docker-compose build web`
  # before this works.
  image: airsched_web
  command: echo I'm a little data container, short and stout...
  volumes:
    - /bundle

