Rails.application.config.assets.precompile += %w(emails.css)
Rails.application.config.assets.precompile += %w(emails.js)
#Rails.application.config.assets.precompile += %w(jquery/jquery.dataTables.fileSize.js)
#Rails.application.config.assets.precompile += %w(jquery/jquery.dataTables.datetime-us.js)
Rails.application.config.assets.precompile += %w(destinations.js destinations.css)
Rails.application.config.assets.precompile += %w(search.js search.css)
# These are assets to pre-compile for fallback CDN failures
Rails.application.config.assets.precompile += %w( jquery/dist/jquery.js )
Rails.application.config.assets.precompile += %w( jquery-ui/jquery-ui.js )
Rails.application.config.assets.precompile += %w( jquery-ui/jquery-ui.js )
Rails.application.config.assets.precompile += %w( font-awesome/scss/font-awesome.scss )
# Rails.application.config.assets.precompile += %w( jquery-ui/ui/core.js jquery-ui/ui/progressbar.js jquery-ui/ui/widget.js)
