default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV["DB_POOL"] || ENV['MAX_THREADS'] || 80 %>
  host: <%= ENV['POSTGRES_PORT_5432_TCP_ADDR'] || 'localhost' %> 
  port: <%= ENV['POSTGRES_PORT_5432_TCP_PORT'] || "5432" %>
  username: demo_ibe_admin
  password: demo_password

development:
  <<: *default
  database: demo_ibe


test:
  <<: *default
  database: air_sched_test


localstaging:
  <<: *default
  database: air_sched_development


production:
  <<: *default
  database: <%= ENV['POSTGRES_DATABASE'] %> 
  username: <%= ENV['POSTGRES_USERNAME'] %> 
  password: <%= ENV['POSTGRES_PASSWORD'] %> 
  host: <%= ENV['POSTGRES_HOST'] %>
