default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: airsched_db_1
  port: <%= ENV['POSTGRES_PORT_5432_TCP_PORT'] || "5432" %>
  username: <%= ENV['POSTGRES_ENV_USER'] ||  "postgres" %>
  password: <%= ENV['POSTGRES_ENV_PASS'] || "" %>

development:
  <<: *default
  database: air_sched_development

localdevelopment:
  <<: *default
  database: <%= ENV['POSTGRES_DATABASE'] %> 
  username: <%= ENV['POSTGRES_USERNAME'] %> 
  password: <%= ENV['POSTGRES_PASSWORD'] %> 
  host: <%= ENV['POSTGRES_HOST'] %>

remotedevelopment:
  <<: *default
  database: <%= ENV['POSTGRES_DATABASE'] %> 
  username: <%= ENV['POSTGRES_USERNAME'] %> 
  password: <%= ENV['POSTGRES_PASSWORD'] %> 
  host: <%= ENV['POSTGRES_HOST'] %>

remotestaging:
  <<: *default
  database: <%= ENV['POSTGRES_DATABASE'] %> 
  username: <%= ENV['POSTGRES_USERNAME'] %> 
  password: <%= ENV['POSTGRES_PASSWORD'] %> 
  host: <%= ENV['POSTGRES_HOST'] %>




test:
  <<: *default
  database: air_sched_test

production:
  <<: *default
  database: <%= ENV['POSTGRES_DATABASE'] %> 
  username: <%= ENV['POSTGRES_USERNAME'] %> 
  password: <%= ENV['POSTGRES_PASSWORD'] %> 
  host: <%= ENV['POSTGRES_HOST'] %>
